//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("AtlasModel", "FK_TA_Person_TA_PersonDetail", "TA_PersonDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PicIntoDb.TA_PersonDetail), "TA_Person", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PicIntoDb.TA_Person), true)]

#endregion

namespace PicIntoDb
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AtlasEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AtlasEntities object using the connection string found in the 'AtlasEntities' section of the application configuration file.
        /// </summary>
        public AtlasEntities() : base("name=AtlasEntities", "AtlasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AtlasEntities object.
        /// </summary>
        public AtlasEntities(string connectionString) : base(connectionString, "AtlasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AtlasEntities object.
        /// </summary>
        public AtlasEntities(EntityConnection connection) : base(connection, "AtlasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TA_Person> TA_Person
        {
            get
            {
                if ((_TA_Person == null))
                {
                    _TA_Person = base.CreateObjectSet<TA_Person>("TA_Person");
                }
                return _TA_Person;
            }
        }
        private ObjectSet<TA_Person> _TA_Person;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TA_PersonDetail> TA_PersonDetail
        {
            get
            {
                if ((_TA_PersonDetail == null))
                {
                    _TA_PersonDetail = base.CreateObjectSet<TA_PersonDetail>("TA_PersonDetail");
                }
                return _TA_PersonDetail;
            }
        }
        private ObjectSet<TA_PersonDetail> _TA_PersonDetail;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TA_Person EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTA_Person(TA_Person tA_Person)
        {
            base.AddObject("TA_Person", tA_Person);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TA_PersonDetail EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTA_PersonDetail(TA_PersonDetail tA_PersonDetail)
        {
            base.AddObject("TA_PersonDetail", tA_PersonDetail);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AtlasModel", Name="TA_Person")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TA_Person : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TA_Person object.
        /// </summary>
        /// <param name="prs_ID">Initial value of the Prs_ID property.</param>
        public static TA_Person CreateTA_Person(global::System.Decimal prs_ID)
        {
            TA_Person tA_Person = new TA_Person();
            tA_Person.Prs_ID = prs_ID;
            return tA_Person;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Prs_ID
        {
            get
            {
                return _Prs_ID;
            }
            set
            {
                if (_Prs_ID != value)
                {
                    OnPrs_IDChanging(value);
                    ReportPropertyChanging("Prs_ID");
                    _Prs_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Prs_ID");
                    OnPrs_IDChanged();
                }
            }
        }
        private global::System.Decimal _Prs_ID;
        partial void OnPrs_IDChanging(global::System.Decimal value);
        partial void OnPrs_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prs_Barcode
        {
            get
            {
                return _Prs_Barcode;
            }
            set
            {
                OnPrs_BarcodeChanging(value);
                ReportPropertyChanging("Prs_Barcode");
                _Prs_Barcode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Prs_Barcode");
                OnPrs_BarcodeChanged();
            }
        }
        private global::System.String _Prs_Barcode;
        partial void OnPrs_BarcodeChanging(global::System.String value);
        partial void OnPrs_BarcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Prs__Param
        {
            get
            {
                return _Prs__Param;
            }
            set
            {
                OnPrs__ParamChanging(value);
                ReportPropertyChanging("Prs__Param");
                _Prs__Param = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prs__Param");
                OnPrs__ParamChanged();
            }
        }
        private Nullable<global::System.Int32> _Prs__Param;
        partial void OnPrs__ParamChanging(Nullable<global::System.Int32> value);
        partial void OnPrs__ParamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Prs_Active
        {
            get
            {
                return _Prs_Active;
            }
            set
            {
                OnPrs_ActiveChanging(value);
                ReportPropertyChanging("Prs_Active");
                _Prs_Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prs_Active");
                OnPrs_ActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _Prs_Active;
        partial void OnPrs_ActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnPrs_ActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prs_CardNum
        {
            get
            {
                return _Prs_CardNum;
            }
            set
            {
                OnPrs_CardNumChanging(value);
                ReportPropertyChanging("Prs_CardNum");
                _Prs_CardNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Prs_CardNum");
                OnPrs_CardNumChanged();
            }
        }
        private global::System.String _Prs_CardNum;
        partial void OnPrs_CardNumChanging(global::System.String value);
        partial void OnPrs_CardNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Prs_DepartmentId
        {
            get
            {
                return _Prs_DepartmentId;
            }
            set
            {
                OnPrs_DepartmentIdChanging(value);
                ReportPropertyChanging("Prs_DepartmentId");
                _Prs_DepartmentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prs_DepartmentId");
                OnPrs_DepartmentIdChanged();
            }
        }
        private Nullable<global::System.Decimal> _Prs_DepartmentId;
        partial void OnPrs_DepartmentIdChanging(Nullable<global::System.Decimal> value);
        partial void OnPrs_DepartmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prs_EmploymentNum
        {
            get
            {
                return _Prs_EmploymentNum;
            }
            set
            {
                OnPrs_EmploymentNumChanging(value);
                ReportPropertyChanging("Prs_EmploymentNum");
                _Prs_EmploymentNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Prs_EmploymentNum");
                OnPrs_EmploymentNumChanged();
            }
        }
        private global::System.String _Prs_EmploymentNum;
        partial void OnPrs_EmploymentNumChanging(global::System.String value);
        partial void OnPrs_EmploymentNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Prs_EmploymentDate
        {
            get
            {
                return _Prs_EmploymentDate;
            }
            set
            {
                OnPrs_EmploymentDateChanging(value);
                ReportPropertyChanging("Prs_EmploymentDate");
                _Prs_EmploymentDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prs_EmploymentDate");
                OnPrs_EmploymentDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Prs_EmploymentDate;
        partial void OnPrs_EmploymentDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPrs_EmploymentDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Prs_ControlStationId
        {
            get
            {
                return _Prs_ControlStationId;
            }
            set
            {
                OnPrs_ControlStationIdChanging(value);
                ReportPropertyChanging("Prs_ControlStationId");
                _Prs_ControlStationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prs_ControlStationId");
                OnPrs_ControlStationIdChanged();
            }
        }
        private Nullable<global::System.Decimal> _Prs_ControlStationId;
        partial void OnPrs_ControlStationIdChanging(Nullable<global::System.Decimal> value);
        partial void OnPrs_ControlStationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Prs_EndEmploymentDate
        {
            get
            {
                return _Prs_EndEmploymentDate;
            }
            set
            {
                OnPrs_EndEmploymentDateChanging(value);
                ReportPropertyChanging("Prs_EndEmploymentDate");
                _Prs_EndEmploymentDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prs_EndEmploymentDate");
                OnPrs_EndEmploymentDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Prs_EndEmploymentDate;
        partial void OnPrs_EndEmploymentDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPrs_EndEmploymentDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Prs_EmployId
        {
            get
            {
                return _Prs_EmployId;
            }
            set
            {
                OnPrs_EmployIdChanging(value);
                ReportPropertyChanging("Prs_EmployId");
                _Prs_EmployId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prs_EmployId");
                OnPrs_EmployIdChanged();
            }
        }
        private Nullable<global::System.Decimal> _Prs_EmployId;
        partial void OnPrs_EmployIdChanging(Nullable<global::System.Decimal> value);
        partial void OnPrs_EmployIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Prs_Sex
        {
            get
            {
                return _Prs_Sex;
            }
            set
            {
                OnPrs_SexChanging(value);
                ReportPropertyChanging("Prs_Sex");
                _Prs_Sex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prs_Sex");
                OnPrs_SexChanged();
            }
        }
        private Nullable<global::System.Boolean> _Prs_Sex;
        partial void OnPrs_SexChanging(Nullable<global::System.Boolean> value);
        partial void OnPrs_SexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prs_Education
        {
            get
            {
                return _Prs_Education;
            }
            set
            {
                OnPrs_EducationChanging(value);
                ReportPropertyChanging("Prs_Education");
                _Prs_Education = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Prs_Education");
                OnPrs_EducationChanged();
            }
        }
        private global::System.String _Prs_Education;
        partial void OnPrs_EducationChanging(global::System.String value);
        partial void OnPrs_EducationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prs_FirstName
        {
            get
            {
                return _Prs_FirstName;
            }
            set
            {
                OnPrs_FirstNameChanging(value);
                ReportPropertyChanging("Prs_FirstName");
                _Prs_FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Prs_FirstName");
                OnPrs_FirstNameChanged();
            }
        }
        private global::System.String _Prs_FirstName;
        partial void OnPrs_FirstNameChanging(global::System.String value);
        partial void OnPrs_FirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Prs_MaritalStatus
        {
            get
            {
                return _Prs_MaritalStatus;
            }
            set
            {
                OnPrs_MaritalStatusChanging(value);
                ReportPropertyChanging("Prs_MaritalStatus");
                _Prs_MaritalStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prs_MaritalStatus");
                OnPrs_MaritalStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _Prs_MaritalStatus;
        partial void OnPrs_MaritalStatusChanging(Nullable<global::System.Int32> value);
        partial void OnPrs_MaritalStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Prs_LastName
        {
            get
            {
                return _Prs_LastName;
            }
            set
            {
                OnPrs_LastNameChanging(value);
                ReportPropertyChanging("Prs_LastName");
                _Prs_LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Prs_LastName");
                OnPrs_LastNameChanged();
            }
        }
        private global::System.String _Prs_LastName;
        partial void OnPrs_LastNameChanging(global::System.String value);
        partial void OnPrs_LastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Prs_PrsDtlID
        {
            get
            {
                return _Prs_PrsDtlID;
            }
            set
            {
                OnPrs_PrsDtlIDChanging(value);
                ReportPropertyChanging("Prs_PrsDtlID");
                _Prs_PrsDtlID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prs_PrsDtlID");
                OnPrs_PrsDtlIDChanged();
            }
        }
        private Nullable<global::System.Decimal> _Prs_PrsDtlID;
        partial void OnPrs_PrsDtlIDChanging(Nullable<global::System.Decimal> value);
        partial void OnPrs_PrsDtlIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Prs_UIValidationGroupID
        {
            get
            {
                return _Prs_UIValidationGroupID;
            }
            set
            {
                OnPrs_UIValidationGroupIDChanging(value);
                ReportPropertyChanging("Prs_UIValidationGroupID");
                _Prs_UIValidationGroupID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prs_UIValidationGroupID");
                OnPrs_UIValidationGroupIDChanged();
            }
        }
        private Nullable<global::System.Decimal> _Prs_UIValidationGroupID;
        partial void OnPrs_UIValidationGroupIDChanging(Nullable<global::System.Decimal> value);
        partial void OnPrs_UIValidationGroupIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AtlasModel", "FK_TA_Person_TA_PersonDetail", "TA_PersonDetail")]
        public TA_PersonDetail TA_PersonDetail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TA_PersonDetail>("AtlasModel.FK_TA_Person_TA_PersonDetail", "TA_PersonDetail").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TA_PersonDetail>("AtlasModel.FK_TA_Person_TA_PersonDetail", "TA_PersonDetail").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TA_PersonDetail> TA_PersonDetailReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TA_PersonDetail>("AtlasModel.FK_TA_Person_TA_PersonDetail", "TA_PersonDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TA_PersonDetail>("AtlasModel.FK_TA_Person_TA_PersonDetail", "TA_PersonDetail", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AtlasModel", Name="TA_PersonDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TA_PersonDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TA_PersonDetail object.
        /// </summary>
        /// <param name="prsDtl_ID">Initial value of the PrsDtl_ID property.</param>
        public static TA_PersonDetail CreateTA_PersonDetail(global::System.Decimal prsDtl_ID)
        {
            TA_PersonDetail tA_PersonDetail = new TA_PersonDetail();
            tA_PersonDetail.PrsDtl_ID = prsDtl_ID;
            return tA_PersonDetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PrsDtl_ID
        {
            get
            {
                return _PrsDtl_ID;
            }
            set
            {
                if (_PrsDtl_ID != value)
                {
                    OnPrsDtl_IDChanging(value);
                    ReportPropertyChanging("PrsDtl_ID");
                    _PrsDtl_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PrsDtl_ID");
                    OnPrsDtl_IDChanged();
                }
            }
        }
        private global::System.Decimal _PrsDtl_ID;
        partial void OnPrsDtl_IDChanging(global::System.Decimal value);
        partial void OnPrsDtl_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_MeliCode
        {
            get
            {
                return _PrsDtl_MeliCode;
            }
            set
            {
                OnPrsDtl_MeliCodeChanging(value);
                ReportPropertyChanging("PrsDtl_MeliCode");
                _PrsDtl_MeliCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_MeliCode");
                OnPrsDtl_MeliCodeChanged();
            }
        }
        private global::System.String _PrsDtl_MeliCode;
        partial void OnPrsDtl_MeliCodeChanging(global::System.String value);
        partial void OnPrsDtl_MeliCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_ShomareShenasname
        {
            get
            {
                return _PrsDtl_ShomareShenasname;
            }
            set
            {
                OnPrsDtl_ShomareShenasnameChanging(value);
                ReportPropertyChanging("PrsDtl_ShomareShenasname");
                _PrsDtl_ShomareShenasname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_ShomareShenasname");
                OnPrsDtl_ShomareShenasnameChanged();
            }
        }
        private global::System.String _PrsDtl_ShomareShenasname;
        partial void OnPrsDtl_ShomareShenasnameChanging(global::System.String value);
        partial void OnPrsDtl_ShomareShenasnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_BirthCertificate
        {
            get
            {
                return _PrsDtl_BirthCertificate;
            }
            set
            {
                OnPrsDtl_BirthCertificateChanging(value);
                ReportPropertyChanging("PrsDtl_BirthCertificate");
                _PrsDtl_BirthCertificate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_BirthCertificate");
                OnPrsDtl_BirthCertificateChanged();
            }
        }
        private global::System.String _PrsDtl_BirthCertificate;
        partial void OnPrsDtl_BirthCertificateChanging(global::System.String value);
        partial void OnPrsDtl_BirthCertificateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_Status
        {
            get
            {
                return _PrsDtl_Status;
            }
            set
            {
                OnPrsDtl_StatusChanging(value);
                ReportPropertyChanging("PrsDtl_Status");
                _PrsDtl_Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_Status");
                OnPrsDtl_StatusChanged();
            }
        }
        private global::System.String _PrsDtl_Status;
        partial void OnPrsDtl_StatusChanging(global::System.String value);
        partial void OnPrsDtl_StatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_FatherName
        {
            get
            {
                return _PrsDtl_FatherName;
            }
            set
            {
                OnPrsDtl_FatherNameChanging(value);
                ReportPropertyChanging("PrsDtl_FatherName");
                _PrsDtl_FatherName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_FatherName");
                OnPrsDtl_FatherNameChanged();
            }
        }
        private global::System.String _PrsDtl_FatherName;
        partial void OnPrsDtl_FatherNameChanging(global::System.String value);
        partial void OnPrsDtl_FatherNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PrsDtl_MilitaryStatus
        {
            get
            {
                return _PrsDtl_MilitaryStatus;
            }
            set
            {
                OnPrsDtl_MilitaryStatusChanging(value);
                ReportPropertyChanging("PrsDtl_MilitaryStatus");
                _PrsDtl_MilitaryStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrsDtl_MilitaryStatus");
                OnPrsDtl_MilitaryStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _PrsDtl_MilitaryStatus;
        partial void OnPrsDtl_MilitaryStatusChanging(Nullable<global::System.Int32> value);
        partial void OnPrsDtl_MilitaryStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_PlaceIssued
        {
            get
            {
                return _PrsDtl_PlaceIssued;
            }
            set
            {
                OnPrsDtl_PlaceIssuedChanging(value);
                ReportPropertyChanging("PrsDtl_PlaceIssued");
                _PrsDtl_PlaceIssued = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_PlaceIssued");
                OnPrsDtl_PlaceIssuedChanged();
            }
        }
        private global::System.String _PrsDtl_PlaceIssued;
        partial void OnPrsDtl_PlaceIssuedChanging(global::System.String value);
        partial void OnPrsDtl_PlaceIssuedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_Tel
        {
            get
            {
                return _PrsDtl_Tel;
            }
            set
            {
                OnPrsDtl_TelChanging(value);
                ReportPropertyChanging("PrsDtl_Tel");
                _PrsDtl_Tel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_Tel");
                OnPrsDtl_TelChanged();
            }
        }
        private global::System.String _PrsDtl_Tel;
        partial void OnPrsDtl_TelChanging(global::System.String value);
        partial void OnPrsDtl_TelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_Address
        {
            get
            {
                return _PrsDtl_Address;
            }
            set
            {
                OnPrsDtl_AddressChanging(value);
                ReportPropertyChanging("PrsDtl_Address");
                _PrsDtl_Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_Address");
                OnPrsDtl_AddressChanged();
            }
        }
        private global::System.String _PrsDtl_Address;
        partial void OnPrsDtl_AddressChanging(global::System.String value);
        partial void OnPrsDtl_AddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_BirthPlace
        {
            get
            {
                return _PrsDtl_BirthPlace;
            }
            set
            {
                OnPrsDtl_BirthPlaceChanging(value);
                ReportPropertyChanging("PrsDtl_BirthPlace");
                _PrsDtl_BirthPlace = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_BirthPlace");
                OnPrsDtl_BirthPlaceChanged();
            }
        }
        private global::System.String _PrsDtl_BirthPlace;
        partial void OnPrsDtl_BirthPlaceChanging(global::System.String value);
        partial void OnPrsDtl_BirthPlaceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PrsDtl_BirthDate
        {
            get
            {
                return _PrsDtl_BirthDate;
            }
            set
            {
                OnPrsDtl_BirthDateChanging(value);
                ReportPropertyChanging("PrsDtl_BirthDate");
                _PrsDtl_BirthDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrsDtl_BirthDate");
                OnPrsDtl_BirthDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PrsDtl_BirthDate;
        partial void OnPrsDtl_BirthDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPrsDtl_BirthDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_R1
        {
            get
            {
                return _PrsDtl_R1;
            }
            set
            {
                OnPrsDtl_R1Changing(value);
                ReportPropertyChanging("PrsDtl_R1");
                _PrsDtl_R1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_R1");
                OnPrsDtl_R1Changed();
            }
        }
        private global::System.String _PrsDtl_R1;
        partial void OnPrsDtl_R1Changing(global::System.String value);
        partial void OnPrsDtl_R1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_R2
        {
            get
            {
                return _PrsDtl_R2;
            }
            set
            {
                OnPrsDtl_R2Changing(value);
                ReportPropertyChanging("PrsDtl_R2");
                _PrsDtl_R2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_R2");
                OnPrsDtl_R2Changed();
            }
        }
        private global::System.String _PrsDtl_R2;
        partial void OnPrsDtl_R2Changing(global::System.String value);
        partial void OnPrsDtl_R2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_R3
        {
            get
            {
                return _PrsDtl_R3;
            }
            set
            {
                OnPrsDtl_R3Changing(value);
                ReportPropertyChanging("PrsDtl_R3");
                _PrsDtl_R3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_R3");
                OnPrsDtl_R3Changed();
            }
        }
        private global::System.String _PrsDtl_R3;
        partial void OnPrsDtl_R3Changing(global::System.String value);
        partial void OnPrsDtl_R3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_R4
        {
            get
            {
                return _PrsDtl_R4;
            }
            set
            {
                OnPrsDtl_R4Changing(value);
                ReportPropertyChanging("PrsDtl_R4");
                _PrsDtl_R4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_R4");
                OnPrsDtl_R4Changed();
            }
        }
        private global::System.String _PrsDtl_R4;
        partial void OnPrsDtl_R4Changing(global::System.String value);
        partial void OnPrsDtl_R4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_R5
        {
            get
            {
                return _PrsDtl_R5;
            }
            set
            {
                OnPrsDtl_R5Changing(value);
                ReportPropertyChanging("PrsDtl_R5");
                _PrsDtl_R5 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_R5");
                OnPrsDtl_R5Changed();
            }
        }
        private global::System.String _PrsDtl_R5;
        partial void OnPrsDtl_R5Changing(global::System.String value);
        partial void OnPrsDtl_R5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_R6
        {
            get
            {
                return _PrsDtl_R6;
            }
            set
            {
                OnPrsDtl_R6Changing(value);
                ReportPropertyChanging("PrsDtl_R6");
                _PrsDtl_R6 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_R6");
                OnPrsDtl_R6Changed();
            }
        }
        private global::System.String _PrsDtl_R6;
        partial void OnPrsDtl_R6Changing(global::System.String value);
        partial void OnPrsDtl_R6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_R7
        {
            get
            {
                return _PrsDtl_R7;
            }
            set
            {
                OnPrsDtl_R7Changing(value);
                ReportPropertyChanging("PrsDtl_R7");
                _PrsDtl_R7 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_R7");
                OnPrsDtl_R7Changed();
            }
        }
        private global::System.String _PrsDtl_R7;
        partial void OnPrsDtl_R7Changing(global::System.String value);
        partial void OnPrsDtl_R7Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_R8
        {
            get
            {
                return _PrsDtl_R8;
            }
            set
            {
                OnPrsDtl_R8Changing(value);
                ReportPropertyChanging("PrsDtl_R8");
                _PrsDtl_R8 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_R8");
                OnPrsDtl_R8Changed();
            }
        }
        private global::System.String _PrsDtl_R8;
        partial void OnPrsDtl_R8Changing(global::System.String value);
        partial void OnPrsDtl_R8Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_R9
        {
            get
            {
                return _PrsDtl_R9;
            }
            set
            {
                OnPrsDtl_R9Changing(value);
                ReportPropertyChanging("PrsDtl_R9");
                _PrsDtl_R9 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_R9");
                OnPrsDtl_R9Changed();
            }
        }
        private global::System.String _PrsDtl_R9;
        partial void OnPrsDtl_R9Changing(global::System.String value);
        partial void OnPrsDtl_R9Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_R10
        {
            get
            {
                return _PrsDtl_R10;
            }
            set
            {
                OnPrsDtl_R10Changing(value);
                ReportPropertyChanging("PrsDtl_R10");
                _PrsDtl_R10 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_R10");
                OnPrsDtl_R10Changed();
            }
        }
        private global::System.String _PrsDtl_R10;
        partial void OnPrsDtl_R10Changing(global::System.String value);
        partial void OnPrsDtl_R10Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_R11
        {
            get
            {
                return _PrsDtl_R11;
            }
            set
            {
                OnPrsDtl_R11Changing(value);
                ReportPropertyChanging("PrsDtl_R11");
                _PrsDtl_R11 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_R11");
                OnPrsDtl_R11Changed();
            }
        }
        private global::System.String _PrsDtl_R11;
        partial void OnPrsDtl_R11Changing(global::System.String value);
        partial void OnPrsDtl_R11Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_R12
        {
            get
            {
                return _PrsDtl_R12;
            }
            set
            {
                OnPrsDtl_R12Changing(value);
                ReportPropertyChanging("PrsDtl_R12");
                _PrsDtl_R12 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_R12");
                OnPrsDtl_R12Changed();
            }
        }
        private global::System.String _PrsDtl_R12;
        partial void OnPrsDtl_R12Changing(global::System.String value);
        partial void OnPrsDtl_R12Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_R13
        {
            get
            {
                return _PrsDtl_R13;
            }
            set
            {
                OnPrsDtl_R13Changing(value);
                ReportPropertyChanging("PrsDtl_R13");
                _PrsDtl_R13 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_R13");
                OnPrsDtl_R13Changed();
            }
        }
        private global::System.String _PrsDtl_R13;
        partial void OnPrsDtl_R13Changing(global::System.String value);
        partial void OnPrsDtl_R13Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_R14
        {
            get
            {
                return _PrsDtl_R14;
            }
            set
            {
                OnPrsDtl_R14Changing(value);
                ReportPropertyChanging("PrsDtl_R14");
                _PrsDtl_R14 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_R14");
                OnPrsDtl_R14Changed();
            }
        }
        private global::System.String _PrsDtl_R14;
        partial void OnPrsDtl_R14Changing(global::System.String value);
        partial void OnPrsDtl_R14Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_R15
        {
            get
            {
                return _PrsDtl_R15;
            }
            set
            {
                OnPrsDtl_R15Changing(value);
                ReportPropertyChanging("PrsDtl_R15");
                _PrsDtl_R15 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_R15");
                OnPrsDtl_R15Changed();
            }
        }
        private global::System.String _PrsDtl_R15;
        partial void OnPrsDtl_R15Changing(global::System.String value);
        partial void OnPrsDtl_R15Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PrsDtl_R16
        {
            get
            {
                return _PrsDtl_R16;
            }
            set
            {
                OnPrsDtl_R16Changing(value);
                ReportPropertyChanging("PrsDtl_R16");
                _PrsDtl_R16 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrsDtl_R16");
                OnPrsDtl_R16Changed();
            }
        }
        private Nullable<global::System.Decimal> _PrsDtl_R16;
        partial void OnPrsDtl_R16Changing(Nullable<global::System.Decimal> value);
        partial void OnPrsDtl_R16Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PrsDtl_R17
        {
            get
            {
                return _PrsDtl_R17;
            }
            set
            {
                OnPrsDtl_R17Changing(value);
                ReportPropertyChanging("PrsDtl_R17");
                _PrsDtl_R17 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrsDtl_R17");
                OnPrsDtl_R17Changed();
            }
        }
        private Nullable<global::System.Decimal> _PrsDtl_R17;
        partial void OnPrsDtl_R17Changing(Nullable<global::System.Decimal> value);
        partial void OnPrsDtl_R17Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PrsDtl_R18
        {
            get
            {
                return _PrsDtl_R18;
            }
            set
            {
                OnPrsDtl_R18Changing(value);
                ReportPropertyChanging("PrsDtl_R18");
                _PrsDtl_R18 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrsDtl_R18");
                OnPrsDtl_R18Changed();
            }
        }
        private Nullable<global::System.Decimal> _PrsDtl_R18;
        partial void OnPrsDtl_R18Changing(Nullable<global::System.Decimal> value);
        partial void OnPrsDtl_R18Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PrsDtl_R19
        {
            get
            {
                return _PrsDtl_R19;
            }
            set
            {
                OnPrsDtl_R19Changing(value);
                ReportPropertyChanging("PrsDtl_R19");
                _PrsDtl_R19 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrsDtl_R19");
                OnPrsDtl_R19Changed();
            }
        }
        private Nullable<global::System.Decimal> _PrsDtl_R19;
        partial void OnPrsDtl_R19Changing(Nullable<global::System.Decimal> value);
        partial void OnPrsDtl_R19Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PrsDtl_R20
        {
            get
            {
                return _PrsDtl_R20;
            }
            set
            {
                OnPrsDtl_R20Changing(value);
                ReportPropertyChanging("PrsDtl_R20");
                _PrsDtl_R20 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrsDtl_R20");
                OnPrsDtl_R20Changed();
            }
        }
        private Nullable<global::System.Decimal> _PrsDtl_R20;
        partial void OnPrsDtl_R20Changing(Nullable<global::System.Decimal> value);
        partial void OnPrsDtl_R20Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_Image
        {
            get
            {
                return _PrsDtl_Image;
            }
            set
            {
                OnPrsDtl_ImageChanging(value);
                ReportPropertyChanging("PrsDtl_Image");
                _PrsDtl_Image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_Image");
                OnPrsDtl_ImageChanged();
            }
        }
        private global::System.String _PrsDtl_Image;
        partial void OnPrsDtl_ImageChanging(global::System.String value);
        partial void OnPrsDtl_ImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_EmailAddress
        {
            get
            {
                return _PrsDtl_EmailAddress;
            }
            set
            {
                OnPrsDtl_EmailAddressChanging(value);
                ReportPropertyChanging("PrsDtl_EmailAddress");
                _PrsDtl_EmailAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_EmailAddress");
                OnPrsDtl_EmailAddressChanged();
            }
        }
        private global::System.String _PrsDtl_EmailAddress;
        partial void OnPrsDtl_EmailAddressChanging(global::System.String value);
        partial void OnPrsDtl_EmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrsDtl_MobileNumber
        {
            get
            {
                return _PrsDtl_MobileNumber;
            }
            set
            {
                OnPrsDtl_MobileNumberChanging(value);
                ReportPropertyChanging("PrsDtl_MobileNumber");
                _PrsDtl_MobileNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrsDtl_MobileNumber");
                OnPrsDtl_MobileNumberChanged();
            }
        }
        private global::System.String _PrsDtl_MobileNumber;
        partial void OnPrsDtl_MobileNumberChanging(global::System.String value);
        partial void OnPrsDtl_MobileNumberChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AtlasModel", "FK_TA_Person_TA_PersonDetail", "TA_Person")]
        public EntityCollection<TA_Person> TA_Person
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TA_Person>("AtlasModel.FK_TA_Person_TA_PersonDetail", "TA_Person");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TA_Person>("AtlasModel.FK_TA_Person_TA_PersonDetail", "TA_Person", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
