update TA_PersonTASpec set prsTA_UIValidationGroupID=null
delete from TA_UIValidationRuleParameter
delete from TA_UIValidationGrouping
delete from TA_UIValidationRuleTempPatameter
delete from TA_UIValidationRulePrecard
delete from TA_UIValidationGroup
delete from TA_UIValidationRule

--Go;

/*   TA_UIValidationRule  ****************/

set identity_insert TA_UIValidationRule on
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('1660','محاسبات هر ماه در روز ___ ماه جاری بسته شود ','4','1','1','1')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('1662','محاسبات در روز ___ ماه قبل بسته شود (مواردی که حقوق را یک ماه دیرتر پرداخت می کنند','5','1','1','2')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('1663','محاسبات از تاریخ ______ بسته شود ','6','1','1','3')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('1664','تعداد درخواستهای تردد عادی پرسنل در ماه حداکثر ___ عدد باشد','7','1','1','39')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('1665','درخواست ترددهای عادی از___ روز قبل تا ___ روز بعد از روز درخواست قابل ثبت باشد','8','1','1','11')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('1666','درخواستهای مرخصی استحقاقی ساعتی از___ روز قبل تا ___ روز بعد از روز درخواست قابل ثبت باشد ','9','1','1','12')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('1668','درخواستهای مرخصی استحقاقی روزانه از___ روز قبل تا ___ روز بعد از روز درخواست قابل ثبت باشد ','10','1','1','13')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('1669','درخواستهای مرخصی بدون حقوق ساعتی از___ روز قبل تا ___ روز بعد از روز درخواست قابل ثبت باشد ','11','1','1','14')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('1670','کلیه درخواست ها از___ روز قبل تا ___ روز بعد از روز درخواست قابل ثبت باشد','24','1','1','10')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('1673','درخواستهای مرخصی بدون حقوق روزانه از___ روز قبل تا ___ روز بعد از روز درخواست قابل ثبت باشد ','12','1','1','15')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('1674','درخواستهای مرخصی استعلاجی ساعتی از___ روز قبل تا ___روز بعد از روز درخواست قابل ثبت باشد ','13','1','1','16')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('1675','درخواستهای مرخصی استعلاجی روزانه از___ روز قبل تا ___ روز بعد از روز درخواست قابل ثبت باشد ','14','1','1','17')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('1679','درخواستهای مجوز اضافه کاری  از___ روز قبل تا ___روز بعد از روز درخواست قابل ثبت باشد ','15','1','1','18')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('1680','تعداد درخواستهای مرخصی استحقاقی ساعتی در ماه حداکثر ___ عدد باشد','16','1','1','30')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('1682','تعداد درخواستهای مرخصی استحقاقی روزانه در ماه حداکثر ___ عدد باشد','17','1','1','31')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('1683','تعداد درخواستهای مرخصی بی حقوق ساعتی در ماه حداکثر ___ عدد باشد','18','1','1','32')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('1685','تعداد درخواستهای مرخصی بی حقوق روزانه در ماه حداکثر ___ عدد باشد','19','1','1','33')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('1686','تعداد درخواستهای مرخصی استعلاجی ساعتی در ماه حداکثر ___ عدد باشد','20','1','1','34')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('1687','تعداد درخواستهای مرخصی استعلاجی روزانه در ماه حداکثر ___ عدد باشد','21','1','1','35')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('1688','تعداد ساعات درخواست مجوز اضافه کاری ___ ساعت در ماه می باشد ','22','1','1','36')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('1691','سقف مرخصی های بدون حقوق در ماه ___ ساعت می باشد','25','0','1','52')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('1693','سقف تعداد مرخصی اول وقت استحقاقی در ماه ___ عدد می باشد','26','0','1','51')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('1','تعداد درخواستهاي مرخصي باحقوق روزانه در سال حداکثر ___ عدد باشد','27','1','1','38')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('2','سقف مقدار مرخصي باحقوق روزانه در نوبت حداکثر ___ روز باشد','28','1','1','53')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('3',' سقف اضافه کار دستوري در ماه ___ ساعت ميباشد و تنها توسط مديران قابل ثبت باشد','29','1','1','54')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('4','مشخص نمودن محل ماموریت اجباری است','30','1','1','55')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('5','مشخص نمودن نام پزشک اجباری است','31','1','1','56')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('6','مشخص نمودن نام بیماری اجباری است','32','1','1','57')
INSERT TA_UIValidationRule(UIRle_ID,UIRle_Name,UIRle_CustomCode,UIRle_Active,UIRle_SubSystemID,uirle_Order) VALUES('7','ثبت مرخصی استحقاقی در صورت داشتن مانده مرخصی مجاز است','33','1','1','58')
set identity_insert TA_UIValidationRule off
/* TA_UIValidationRulePrecard  *************************/
set identity_insert TA_UIValidationRulePrecard on
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('1','8','0')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('2','7','0')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('3','9','21')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('4','10','41')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('5','11','11')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('6','11','12')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('7','11','13')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('8','11','14')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('9','11','15')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('10','12','31')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('11','12','32')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('12','12','33')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('13','12','34')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('14','12','35')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('15','13','22')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('16','14','42')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('17','15','125')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('18','16','21')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('19','17','41')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('20','18','11')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('21','18','12')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('22','18','13')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('23','18','14')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('24','18','15')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('25','19','31')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('26','19','32')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('27','19','33')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('28','19','34')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('29','19','35')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('30','20','22')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('31','21','42')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('32','22','125')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('33','27','43')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('34','28','43')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('35','29','121')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('36','27','44')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('37','28','44')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('38','29','121')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('39','30','61')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('40','30','62')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('41','30','63')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('42','30','64')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('43','30','65')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('44','31','22')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('45','31','42')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('46','32','22')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('47','32','42')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('48','33','21')
INSERT TA_UIValidationRulePrecard(UIRlePrecard_ID,UIRlePrecard_RuleCustomCode,UIRlePrecard_PrecardCustomCode) VALUES('49','33','41')
set identity_insert TA_UIValidationRulePrecard off
/*  TA_UIValidationRuleTempPatameter         ************************/

set identity_insert TA_UIValidationRuleTempPatameter on
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1','0','تعداد روز قبل از درخواست','1670','BeforeDayCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('2','0','تعداد روز بعد از درخواست','1670','AfterDayCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('3','0','تعداد روز درخواست','1','MaxCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('4','0','سقف مقدار روز درخواست','2','DayCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('5','1','تعداد روز درخواست','3','MaxDasturyOverwork')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1465','0','روز بستن','1660','LockCalculationFromCurrentMonth')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1467','0','روز بستن','1662','LockCalculationFromBeforeMonth')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1469','2','تاریخ بستن محاسبات','1663','LockCalculationFromDate')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1470','0','حداکثر تردد','1664','MaxTrafficRequestInMonth')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1471','0','تعداد روز بعد از درخواست','1665','AllowedTrafficRequestAfterTime')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1472','0','ابتدای زمان مجاز مرخصی استحقاقی س','1666','BeforeDayCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1474','0','انتهای زمان مجاز مرخصی استحقاقی س','1666','AfterDayCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1476','0','ابتدای زمان مجاز مرخصی استحقاقی ر','1668','BeforeDayCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1477','0','انتهای زمان مجاز مرخصی استحقاقی ر','1668','AfterDayCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1478','0','ابتدای زمان مجاز مرخصی بدون حقوق س','1669','BeforeDayCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1479','0','انتهای زمان مجاز مرخصی بدون حقوق س','1669','AfterDayCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1481','0','ابتدای زمان مجاز مرخصی بدون حقوق ر','1673','BeforeDayCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1483','0','انتهای زمان مجاز مرخصی بدون حقوق ر','1673','AfterDayCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1484','0','ابتدای زمان مجاز مرخصی استعلاجی س','1674','BeforeDayCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1486','0','اتنهای زمان مجاز مرخصی استعلاجی س','1674','AfterDayCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1487','0','ابتدای زمان مجاز مرخصی استعلاجی ر','1675','BeforeDayCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1489','0','انتهای زمان مجاز مرخصی استعلاجی ر','1675','AfterDayCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1491','0','ابتدای زمان مجاز مجوز اضافه کاری','1679','BeforeDayCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1492','0','انتهای زمان مجاز مجوز اضافه کاری','1679','AfterDayCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1493','0','تعداد مرخصی استحقاقی ساعتی','1680','MaxCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1494','0','تعداد مرخصی استحقاقی روزانه','1682','MaxCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1495','0','تعداد مرخصی بدون حقوق ساعتی','1683','MaxCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1499','0','تعداد مرخصی بدون حقوق روزانه','1685','MaxCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1500','0','تعداد مرخصی استعلاجی ساعتی','1686','MaxCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1502','0','تعداد مرخصی استعلاجی روزانه','1687','MaxCount')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1503','1','ساعات مجاز مجوز اضافه کاری','1688','MaxHrours')
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1508','1','مرخصی بدون حقوق در ماه','1691',NULL)
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1509','0','مرخصی  استحقاقی اول وقت در ماه','1693',NULL)
INSERT TA_UIValidationRuleTempPatameter(UIValTmpParam_ID,UIValTmpParam_type,UIValTmpParam_Name,UIValTmpParam_RuleID,UIValTmpParam_KeyName) VALUES('1510','0','تعداد روز قبل از درخواست','1665','AllowedTrafficRequestBeforeTime')

set identity_insert TA_UIValidationRuleTempPatameter off