select [rule_code] as rulecat_id, [rule_name] as rulecat_name,
case   isnull( [Rule_EMojavvez]	     ,'0') when 0 then '' else cast( [Rule_EMojavvez]			as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EMojavvezafter] ,'0') when 0 then '' else cast( [Rule_EMojavvezafter]		as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_emojazday]	     ,'0') when 0 then '' else cast( [Rule_emojazday]			as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_emojazdayg]     ,'0') when 0 then '' else cast( [Rule_emojazdayg]			as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EMinG]		     ,'0') when 0 then '' else cast( [Rule_EMinG]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EMinB]		     ,'0') when 0 then '' else cast( [Rule_EMinB]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EMAXG]		     ,'0') when 0 then '' else cast( [Rule_EMAXG]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EMAxB]		     ,'0') when 0 then '' else cast( [Rule_EMAxB]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EMAXA]		     ,'0') when 0 then '' else cast( [Rule_EMAXA]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EMAxT]		     ,'0') when 0 then '' else cast( [Rule_EMAxT]				as nvarchar(max)) end as '158 ' ,
case   isnull( [Rule_EMaxM]		     ,'0') when 0 then '' else cast( [Rule_EMaxM]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EMaxTM]	     ,'0') when 0 then '' else cast( [Rule_EMaxTM]				as nvarchar(max)) end as '159 ' ,
case   isnull( [Rule_EFix]		     ,'0') when 0 then '' else cast( [Rule_EFix]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EZA]		     ,'0') when 0 then '' else cast( [Rule_EZA]					as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EZATime]	     ,'0') when 0 then '' else cast( [Rule_EZATime]				as nvarchar(max)) end as '163 ' ,
case   isnull( [Rule_EZA1]		     ,'0') when 0 then '' else cast( [Rule_EZA1]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EZT]		     ,'0') when 0 then '' else cast( [Rule_EZT]					as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EZTTime]	     ,'0') when 0 then '' else cast( [Rule_EZTTime]				as nvarchar(max)) end as '164 ' ,
case   isnull( [Rule_EZT1]		     ,'0') when 0 then '' else cast( [Rule_EZT1]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EZG]		     ,'0') when 0 then '' else cast( [Rule_EZG]					as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EZGTime]	     ,'0') when 0 then '' else cast( [Rule_EZGTime]				as nvarchar(max)) end as '165 ' ,
case   isnull( [Rule_EZG1]		     ,'0') when 0 then '' else cast( [Rule_EZG1]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EZR]		     ,'0') when 0 then '' else cast( [Rule_EZR]					as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EZRTime]	     ,'0') when 0 then '' else cast( [Rule_EZRTime]				as nvarchar(max)) end as '166 ' ,
case   isnull( [Rule_EZR1]		     ,'0') when 0 then '' else cast( [Rule_EZR1]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EZshab]	     ,'0') when 0 then '' else cast( [Rule_EZshab]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EZshabTime]     ,'0') when 0 then '' else cast( [Rule_EZshabTime]			as nvarchar(max)) end as '167 ' ,
case   isnull( [Rule_EZshab1]	     ,'0') when 0 then '' else cast( [Rule_EZshab1]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EZshabt]	     ,'0') when 0 then '' else cast( [Rule_EZshabt]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EZshabtTime]    ,'0') when 0 then '' else cast( [Rule_EZshabtTime]			as nvarchar(max)) end as '168 ' ,
case   isnull( [Rule_EZshabt1]	     ,'0') when 0 then '' else cast( [Rule_EZshabt1]			as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EMSHR]		     ,'0') when 0 then '' else cast( [Rule_EMSHR]				as nvarchar(max)) end as '167 ' ,
case   isnull( [Rule_EMSHRt]	     ,'0') when 0 then '' else cast( [Rule_EMSHRt]				as nvarchar(max)) end as '167 ' ,
case   isnull( [Rule_EMDay]		     ,'0') when 0 then '' else cast( [Rule_EMDay]				as nvarchar(max)) end as '168 ' ,
case   isnull( [Rule_EMDayt]	     ,'0') when 0 then '' else cast( [Rule_EMDayt]				as nvarchar(max)) end as '168 ' ,
case   isnull( [Rule_etk]		     ,'0') when 0 then '' else cast( [Rule_etk]					as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_ehd]		     ,'0') when 0 then '' else cast( [Rule_ehd]					as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_Eba]		     ,'0') when 0 then '' else cast( [Rule_Eba]					as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_egm]		     ,'0') when 0 then '' else cast( [Rule_egm]					as nvarchar(max)) end as '184 ' ,
case   isnull( [Rule_e28fullmomtad]  ,'0') when 0 then '' else cast( [Rule_e28fullmomtad]		as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_emzero]	     ,'0') when 0 then '' else cast( [Rule_emzero]				as nvarchar(max)) end as '185 ' ,
case   isnull( [Rule_EMa]		     ,'0') when 0 then '' else cast( [Rule_EMa]					as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EZMa]		     ,'0') when 0 then '' else cast( [Rule_EZMa]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EMo]		     ,'0') when 0 then '' else cast( [Rule_EMo]					as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_EZMo]		     ,'0') when 0 then '' else cast( [Rule_EZMo]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_edkeshik]	     ,'0') when 0 then '' else cast( [Rule_edkeshik]			as nvarchar(max)) end as '175 ' ,
case   isnull( [Rule_enoworkday]     ,'0') when 0 then '' else cast( [Rule_enoworkday]			as nvarchar(max)) end as '176 ' ,
case   isnull( [Rule_enoworkkasr]    ,'0') when 0 then '' else cast( [Rule_enoworkkasr]			as nvarchar(max)) end as '176 ' ,
case   isnull( [Rule_eghabl1]	     ,'0') when 0 then '' else cast( [Rule_eghabl1]				as nvarchar(max)) end as '177 ' ,
case   isnull( [Rule_eghabl2]	     ,'0') when 0 then '' else cast( [Rule_eghabl2]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_ebaad1]	     ,'0') when 0 then '' else cast( [Rule_ebaad1]				as nvarchar(max)) end as '178 ' ,
case   isnull( [Rule_ebaad2]	     ,'0') when 0 then '' else cast( [Rule_ebaad2]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_ebaad11]	     ,'0') when 0 then '' else cast( [Rule_ebaad11]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_ebaad12]	     ,'0') when 0 then '' else cast( [Rule_ebaad12]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_ebaad21]	     ,'0') when 0 then '' else cast( [Rule_ebaad21]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_ebaad22]	     ,'0') when 0 then '' else cast( [Rule_ebaad22]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_egkl]		     ,'0') when 0 then '' else cast( [Rule_egkl]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_egknahar]	     ,'0') when 0 then '' else cast( [Rule_egknahar]			as nvarchar(max)) end as '181 ' ,
case   isnull( [Rule_egtlimit]	     ,'0') when 0 then '' else cast( [Rule_egtlimit]			as nvarchar(max)) end as '182 ' ,
case   isnull( [Rule_egfrom]	     ,'0') when 0 then '' else cast( [Rule_egfrom]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_egto]		     ,'0') when 0 then '' else cast( [Rule_egto]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_GMT1]		     ,'0') when 0 then '' else cast( [Rule_GMT1]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_GMT2]		     ,'0') when 0 then '' else cast( [Rule_GMT2]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_GMB]		     ,'0') when 0 then '' else cast( [Rule_GMB]					as nvarchar(max)) end as '40  ' ,
case   isnull( [Rule_GMT1m]		     ,'0') when 0 then '' else cast( [Rule_GMT1m]				as nvarchar(max)) end as '41  ' ,
case   isnull( [Rule_GMT2m]		     ,'0') when 0 then '' else cast( [Rule_GMT2m]				as nvarchar(max)) end as '42  ' ,
case   isnull( [Rule_GMBm]		     ,'0') when 0 then '' else cast( [Rule_GMBm]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_GMaxD]		     ,'0') when 0 then '' else cast( [Rule_GMaxD]				as nvarchar(max)) end as '44  ' ,
case   isnull( [Rule_GMaxM]		     ,'0') when 0 then '' else cast( [Rule_GMaxM]				as nvarchar(max)) end as '45  ' ,
case   isnull( [Rule_ggmezmanfi]     ,'0') when 0 then '' else cast( [Rule_ggmezmanfi]			as nvarchar(max)) end as '46  ' ,
case   isnull( [Rule_GPAS]		     ,'0') when 0 then '' else cast( [Rule_GPAS]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_GZPAS]		     ,'0') when 0 then '' else cast( [Rule_GZPAS]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_GSLimit]	     ,'0') when 0 then '' else cast( [Rule_GSLimit]				as nvarchar(max)) end as '48  ' ,
case   isnull( [Rule_gtajilLimit]    ,'0') when 0 then '' else cast( [Rule_gtajilLimit]			as nvarchar(max)) end as '49  ' ,
case   isnull( [Rule_gmorbigh]	     ,'0') when 0 then '' else cast( [Rule_gmorbigh]			as nvarchar(max)) end as '50  ' ,
case   isnull( [Rule_gafvm]		     ,'0') when 0 then '' else cast( [Rule_gafvm]				as nvarchar(max)) end as '52  ' ,
case   isnull( [Rule_gafvlimit]	     ,'0') when 0 then '' else cast( [Rule_gafvlimit]			as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_gjanbaz]	     ,'0') when 0 then '' else cast( [Rule_gjanbaz]				as nvarchar(max)) end as '55  ' ,
case   isnull( [Rule_gjanbazEmor]    ,'0') when 0 then '' else cast( [Rule_gjanbazEmor]			as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_gddouble]	     ,'0') when 0 then '' else cast( [Rule_gddouble]			as nvarchar(max)) end as '60  ' ,
case   isnull( [Rule_GTMM]		     ,'0') when 0 then '' else cast( [Rule_GTMM]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_GTSM]		     ,'0') when 0 then '' else cast( [Rule_GTSM]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_GKBH]		     ,'0') when 0 then '' else cast( [Rule_GKBH]				as nvarchar(max)) end as '58  ' ,
case   isnull( [Rule_GKBM]		     ,'0') when 0 then '' else cast( [Rule_GKBM]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_GTF1]		     ,'0') when 0 then '' else cast( [Rule_GTF1]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_GTE1]		     ,'0') when 0 then '' else cast( [Rule_GTE1]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_GTP1]		     ,'0') when 0 then '' else cast( [Rule_GTP1]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_GTF2]		     ,'0') when 0 then '' else cast( [Rule_GTF2]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_GTE2]		     ,'0') when 0 then '' else cast( [Rule_GTE2]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_GTP2]		     ,'0') when 0 then '' else cast( [Rule_GTP2]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_GTF3]		     ,'0') when 0 then '' else cast( [Rule_GTF3]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_GTE3]		     ,'0') when 0 then '' else cast( [Rule_GTE3]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_GTP3]		     ,'0') when 0 then '' else cast( [Rule_GTP3]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_gsmt1]		     ,'0') when 0 then '' else cast( [Rule_gsmt1]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_gsmp1]		     ,'0') when 0 then '' else cast( [Rule_gsmp1]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_gsmt2]		     ,'0') when 0 then '' else cast( [Rule_gsmt2]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_gsmp2]		     ,'0') when 0 then '' else cast( [Rule_gsmp2]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_gsmp3]		     ,'0') when 0 then '' else cast( [Rule_gsmp3]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_GZHD]		     ,'0') when 0 then '' else cast( [Rule_GZHD]				as nvarchar(max)) end as '67  ' ,
case   isnull( [Rule_GEBEIN]	     ,'0') when 0 then '' else cast( [Rule_GEBEIN]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_gslastm]	     ,'0') when 0 then '' else cast( [Rule_gslastm]				as nvarchar(max)) end as '59  ' ,
case   isnull( [Rule_Gttm]		     ,'0') when 0 then '' else cast( [Rule_Gttm]				as nvarchar(max)) end as '61  ' ,
case   isnull( [Rule_Gttmj]		     ,'0') when 0 then '' else cast( [Rule_Gttmj]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_gNaghes]	     ,'0') when 0 then '' else cast( [Rule_gNaghes]				as nvarchar(max)) end as '62  ' ,
case   isnull( [Rule_GD]		     ,'0') when 0 then '' else cast( [Rule_GD]					as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_GBD]		     ,'0') when 0 then '' else cast( [Rule_GBD]					as nvarchar(max)) end as '66  ' ,
case   isnull( [Rule_GKD]		     ,'0') when 0 then '' else cast( [Rule_GKD]					as nvarchar(max)) end as '66  ' ,
case   isnull( [Rule_GRZHD]		     ,'0') when 0 then '' else cast( [Rule_GRZHD]				as nvarchar(max)) end as '67  ' ,
case   isnull( [Rule_MAHR]		     ,'0') when 0 then '' else cast( [Rule_MAHR]				as nvarchar(max)) end as '141 ' ,
case   isnull( [Rule_mamax]		     ,'0') when 0 then '' else cast( [Rule_mamax]				as nvarchar(max)) end as '122 ' ,
case   isnull( [Rule_MAkar]		     ,'0') when 0 then '' else cast( [Rule_MAkar]				as nvarchar(max)) end as '125 ' ,
case   isnull( [Rule_Makarna]	     ,'0') when 0 then '' else cast( [Rule_Makarna]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_MARMTM]	     ,'0') when 0 then '' else cast( [Rule_MARMTM]				as nvarchar(max)) end as '204 ' ,
case   isnull( [Rule_MASHRMTM]	     ,'0') when 0 then '' else cast( [Rule_MASHRMTM]			as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_MARMRM]	     ,'0') when 0 then '' else cast( [Rule_MARMRM]				as nvarchar(max)) end as '204 ' ,
case   isnull( [Rule_MASHRMRM]	     ,'0') when 0 then '' else cast( [Rule_MASHRMRM]			as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_MARMGM]	     ,'0') when 0 then '' else cast( [Rule_MARMGM]				as nvarchar(max)) end as '204 ' ,
case   isnull( [Rule_MASHRMGM]	     ,'0') when 0 then '' else cast( [Rule_MASHRMGM]			as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_MAGE]		     ,'0') when 0 then '' else cast( [Rule_MAGE]				as nvarchar(max)) end as '132 ' ,
case   isnull( [Rule_MAms1]		     ,'0') when 0 then '' else cast( [Rule_MAms1]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_MAsg]		     ,'0') when 0 then '' else cast( [Rule_MAsg]				as nvarchar(max)) end as '133 ' ,
case   isnull( [Rule_MAsn]		     ,'0') when 0 then '' else cast( [Rule_MAsn]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_manowbat]	     ,'0') when 0 then '' else cast( [Rule_manowbat]			as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_manokez]	     ,'0') when 0 then '' else cast( [Rule_manokez]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_MArshgs]	     ,'0') when 0 then '' else cast( [Rule_MArshgs]				as nvarchar(max)) end as '139 ' ,
case   isnull( [Rule_mamojavvez]     ,'0') when 0 then '' else cast( [Rule_mamojavvez]			as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_mamtomor]	     ,'0') when 0 then '' else cast( [Rule_mamtomor]			as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_MAD]		     ,'0') when 0 then '' else cast( [Rule_MAD]					as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_MAB1]		     ,'0') when 0 then '' else cast( [Rule_MAB1]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_MAK1]		     ,'0') when 0 then '' else cast( [Rule_MAK1]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_MARHR]		     ,'0') when 0 then '' else cast( [Rule_MARHR]				as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_MAdFixh]	     ,'0') when 0 then '' else cast( [Rule_MAdFixh]				as nvarchar(max)) end as '142 ' ,
case   isnull( [Rule_EhMojavvez]     ,'0') when 0 then '' else cast( [Rule_EhMojavvez]			as nvarchar(max)) end as 'code' ,
case   isnull( [Rule_gjanbazIgnore]  ,'0') when 0 then '' else cast( [Rule_gjanbazIgnore]		as nvarchar(max)) end as 'code' 						

,rule2.*
from clock.dbo.rules



as rule1
join
(



SELECT [Rule_Code] as rulecat_id,
case   isnull( [Rule_MOHR]				,'0') when 0 then '' else cast( [Rule_MOHR]				as nvarchar(max)) end as 'n001' , 
case   isnull( [Rule_MOEY]				,'0') when 0 then '' else cast( [Rule_MOEY]				as nvarchar(max)) end as 'n002' , 
case   isnull( [Rule_MOafv]				,'0') when 0 then '' else cast( [Rule_MOafv]			as nvarchar(max)) end as 'n003' , 
case   isnull( [Rule_MOafvlimit]	    ,'0') when 0 then '' else cast( [Rule_MOafvlimit]		as nvarchar(max)) end as 'n004' ,
case   isnull( [Rule_MOhd]				,'0') when 0 then '' else cast( [Rule_MOhd]				as nvarchar(max)) end as 'n005' , 
case   isnull( [Rule_MOhdg]				,'0') when 0 then '' else cast( [Rule_MOhdg]			as nvarchar(max)) end as 'n006' , 
case   isnull( [Rule_MOesl]				,'0') when 0 then '' else cast( [Rule_MOesl]			as nvarchar(max)) end as 'n007' , 
case   isnull( [Rule_MOesyl]			,'0') when 0 then '' else cast( [Rule_MOesyl]			as nvarchar(max)) end as 'n008' , 
case   isnull( [Rule_moesmin]			,'0') when 0 then '' else cast( [Rule_moesmin]			as nvarchar(max)) end as 'n009' ,
case   isnull( [Rule_MOesn]				,'0') when 0 then '' else cast( [Rule_MOesn]			as nvarchar(max)) end as 'n010' , 
case   isnull( [Rule_MOesf]				,'0') when 0 then '' else cast( [Rule_MOesf]			as nvarchar(max)) end as 'n011' , 
case   isnull( [Rule_MOepl]				,'0') when 0 then '' else cast( [Rule_MOepl]			as nvarchar(max)) end as 'n012' , 
case   isnull( [Rule_MOepls]			,'0') when 0 then '' else cast( [Rule_MOepls]			as nvarchar(max)) end as 'n013' , 
case   isnull( [Rule_MOeal]				,'0') when 0 then '' else cast( [Rule_MOeal]			as nvarchar(max)) end as 'n014' , 
case   isnull( [Rule_MOsy]				,'0') when 0 then '' else cast( [Rule_MOsy]				as nvarchar(max)) end as 'n015' , 
case   isnull( [Rule_MOsm]				,'0') when 0 then '' else cast( [Rule_MOsm]				as nvarchar(max)) end as 'n016' , 
case   isnull( [Rule_moeneg]			,'0') when 0 then '' else cast( [Rule_moeneg]			as nvarchar(max)) end as 'n017' , 
case   isnull( [Rule_MOeb]				,'0') when 0 then '' else cast( [Rule_MOeb]				as nvarchar(max)) end as 'n018' , 
case   isnull( [Rule_MOebs]				,'0') when 0 then '' else cast( [Rule_MOebs]			as nvarchar(max)) end as 'n019' , 
case   isnull( [Rule_MOTalab]			,'0') when 0 then '' else cast( [Rule_MOTalab]			as nvarchar(max)) end as 'n020' ,
case   isnull( [Rule_MOKAR]				,'0') when 0 then '' else cast( [Rule_MOKAR]			as nvarchar(max)) end as 'n021' , 
case   isnull( [Rule_MOKARNA]			,'0') when 0 then '' else cast( [Rule_MOKARNA]			as nvarchar(max)) end as 'n022' ,
case   isnull( [Rule_MOH]				,'0') when 0 then '' else cast( [Rule_MOH]				as nvarchar(max)) end as 'n023' , 
case   isnull( [Rule_MOB1]				,'0') when 0 then '' else cast( [Rule_MOB1]				as nvarchar(max)) end as 'n024' , 
case   isnull( [Rule_MOK1]				,'0') when 0 then '' else cast( [Rule_MOK1]				as nvarchar(max)) end as 'n025' , 
case   isnull( [Rule_MORHR]				,'0') when 0 then '' else cast( [Rule_MORHR]			as nvarchar(max)) end as 'n026' , 
case   isnull( [Rule_MOMTM]				,'0') when 0 then '' else cast( [Rule_MOMTM]			as nvarchar(max)) end as 'n027' , 
case   isnull( [Rule_MOMRM]				,'0') when 0 then '' else cast( [Rule_MOMRM]			as nvarchar(max)) end as 'n028' , 
case   isnull( [Rule_MOMGM]				,'0') when 0 then '' else cast( [Rule_MOMGM]			as nvarchar(max)) end as 'n029' , 
case   isnull( [Rule_MOMTMs]			,'0') when 0 then '' else cast( [Rule_MOMTMs]			as nvarchar(max)) end as 'n030' , 
case   isnull( [Rule_MOMRMs]			,'0') when 0 then '' else cast( [Rule_MOMRMs]			as nvarchar(max)) end as 'n031' , 
case   isnull( [Rule_MOMGMs]			,'0') when 0 then '' else cast( [Rule_MOMGMs]			as nvarchar(max)) end as 'n032' , 
case   isnull( [Rule_monowrooz]			,'0') when 0 then '' else cast( [Rule_monowrooz]		as nvarchar(max)) end as 'n033' ,
case   isnull( [Rule_morgkok]			,'0') when 0 then '' else cast( [Rule_morgkok]			as nvarchar(max)) end as 'n034' ,
case   isnull( [Rule_morsbiok]			,'0') when 0 then '' else cast( [Rule_morsbiok]			as nvarchar(max)) end as 'n035' ,
case   isnull( [Rule_mobislastm]	    ,'0') when 0 then '' else cast( [Rule_mobislastm]		as nvarchar(max)) end as 'n036' ,
case   isnull( [Rule_MOMs1]				,'0') when 0 then '' else cast( [Rule_MOMs1]			as nvarchar(max)) end as 'n037' , 
case   isnull( [Rule_mout]				,'0') when 0 then '' else cast( [Rule_mout]				as nvarchar(max)) end as 'n038' , 
case   isnull( [Rule_monowbat]			,'0') when 0 then '' else cast( [Rule_monowbat]			as nvarchar(max)) end as 'n039' ,
case   isnull( [Rule_moezcode]			,'0') when 0 then '' else cast( [Rule_moezcode]			as nvarchar(max)) end as 'n040' ,
case   isnull( [Rule_moezkasr]			,'0') when 0 then '' else cast( [Rule_moezkasr]			as nvarchar(max)) end as 'n041' ,
case   isnull( [Rule_morbies]			,'0') when 0 then '' else cast( [Rule_morbies]			as nvarchar(max)) end as 'n042' ,
case   isnull( [Rule_moghes]			,'0') when 0 then '' else cast( [Rule_moghes]			as nvarchar(max)) end as 'n043' , 
case   isnull( [Rule_momojavvez]		,'0') when 0 then '' else cast( [Rule_momojavvez]		as nvarchar(max)) end as 'n044' ,
case   isnull( [Rule_moeylist]			,'0') when 0 then '' else cast( [Rule_moeylist]			as nvarchar(max)) end as 'n045' ,
case   isnull( [Rule_moeyd1]			,'0') when 0 then '' else cast( [Rule_moeyd1]			as nvarchar(max)) end as 'n046' , 
case   isnull( [Rule_moeyd2]			,'0') when 0 then '' else cast( [Rule_moeyd2]			as nvarchar(max)) end as 'n047' , 
case   isnull( [Rule_moeyd3]			,'0') when 0 then '' else cast( [Rule_moeyd3]			as nvarchar(max)) end as 'n048' , 
case   isnull( [Rule_moeyd4]			,'0') when 0 then '' else cast( [Rule_moeyd4]			as nvarchar(max)) end as 'n049' , 
case   isnull( [Rule_moeyd5]			,'0') when 0 then '' else cast( [Rule_moeyd5]			as nvarchar(max)) end as 'n050' , 
case   isnull( [Rule_moeyd6]			,'0') when 0 then '' else cast( [Rule_moeyd6]			as nvarchar(max)) end as 'n051' , 
case   isnull( [Rule_moeyd7]			,'0') when 0 then '' else cast( [Rule_moeyd7]			as nvarchar(max)) end as 'n052' , 
case   isnull( [Rule_moeyd8]			,'0') when 0 then '' else cast( [Rule_moeyd8]			as nvarchar(max)) end as 'n053' , 
case   isnull( [Rule_moeyd9]			,'0') when 0 then '' else cast( [Rule_moeyd9]			as nvarchar(max)) end as 'n054' , 
case   isnull( [Rule_moeyd10]			,'0') when 0 then '' else cast( [Rule_moeyd10]			as nvarchar(max)) end as 'n055' ,
case   isnull( [Rule_moeyd11]			,'0') when 0 then '' else cast( [Rule_moeyd11]			as nvarchar(max)) end as 'n056' ,
case   isnull( [Rule_moeyd12]			,'0') when 0 then '' else cast( [Rule_moeyd12]			as nvarchar(max)) end as 'n057' ,
case   isnull( [Rule_moeyh1]			,'0') when 0 then '' else cast( [Rule_moeyh1]			as nvarchar(max)) end as 'n058' , 
case   isnull( [Rule_moeyh2]			,'0') when 0 then '' else cast( [Rule_moeyh2]			as nvarchar(max)) end as 'n059' , 
case   isnull( [Rule_moeyh3]			,'0') when 0 then '' else cast( [Rule_moeyh3]			as nvarchar(max)) end as 'n060' , 
case   isnull( [Rule_moeyh4]			,'0') when 0 then '' else cast( [Rule_moeyh4]			as nvarchar(max)) end as 'n061' , 
case   isnull( [Rule_moeyh5]			,'0') when 0 then '' else cast( [Rule_moeyh5]			as nvarchar(max)) end as 'n062' , 
case   isnull( [Rule_moeyh6]			,'0') when 0 then '' else cast( [Rule_moeyh6]			as nvarchar(max)) end as 'n063' , 
case   isnull( [Rule_moeyh7]			,'0') when 0 then '' else cast( [Rule_moeyh7]			as nvarchar(max)) end as 'n064' , 
case   isnull( [Rule_moeyh8]			,'0') when 0 then '' else cast( [Rule_moeyh8]			as nvarchar(max)) end as 'n065' , 
case   isnull( [Rule_moeyh9]			,'0') when 0 then '' else cast( [Rule_moeyh9]			as nvarchar(max)) end as 'n066' , 
case   isnull( [Rule_moeyh10]			,'0') when 0 then '' else cast( [Rule_moeyh10]			as nvarchar(max)) end as 'n067' ,
case   isnull( [Rule_moeyh11]			,'0') when 0 then '' else cast( [Rule_moeyh11]			as nvarchar(max)) end as 'n068' ,
case   isnull( [Rule_moeyh12]			,'0') when 0 then '' else cast( [Rule_moeyh12]			as nvarchar(max)) end as 'n069' ,
case   isnull( [Rule_DTKAR]				,'0') when 0 then '' else cast( [Rule_DTKAR]			as nvarchar(max)) end as 'n070' , 
case   isnull( [Rule_DGKAR]				,'0') when 0 then '' else cast( [Rule_DGKAR]			as nvarchar(max)) end as 'n071' , 
case   isnull( [Rule_DRKAR]				,'0') when 0 then '' else cast( [Rule_DRKAR]			as nvarchar(max)) end as 'n072' , 
case   isnull( [Rule_KarD]				,'0') when 0 then '' else cast( [Rule_KarD]				as nvarchar(max)) end as 'n073' , 
case   isnull( [Rule_KarB1]				,'0') when 0 then '' else cast( [Rule_KarB1]			as nvarchar(max)) end as 'n074' , 
case   isnull( [Rule_KarK1]				,'0') when 0 then '' else cast( [Rule_KarK1]			as nvarchar(max)) end as 'n075' , 
case   isnull( [Rule_KarT]				,'0') when 0 then '' else cast( [Rule_KarT]				as nvarchar(max)) end as 'n076' , 
case   isnull( [Rule_KarR]				,'0') when 0 then '' else cast( [Rule_KarR]				as nvarchar(max)) end as 'n077' , 
case   isnull( [Rule_KarSaati]			,'0') when 0 then '' else cast( [Rule_KarSaati]			as nvarchar(max)) end as 'n078' ,
case   isnull( [Rule_Karlazem]			,'0') when 0 then '' else cast( [Rule_Karlazem]			as nvarchar(max)) end as 'n079' ,
case   isnull( [Rule_KarPerday]			,'0') when 0 then '' else cast( [Rule_KarPerday]		as nvarchar(max)) end as 'n080' ,
case   isnull( [Rule_KarPercent]	    ,'0') when 0 then '' else cast( [Rule_KarPercent]		as nvarchar(max)) end as 'n081' ,
case   isnull( [Rule_KarPGroup]			,'0') when 0 then '' else cast( [Rule_KarPGroup]		as nvarchar(max)) end as 'n082' ,
case   isnull( [Rule_KarSaat]			,'0') when 0 then '' else cast( [Rule_KarSaat]			as nvarchar(max)) end as 'n083' ,
case   isnull( [Rule_karpermah1]	    ,'0') when 0 then '' else cast( [Rule_karpermah1]		as nvarchar(max)) end as 'n084' ,
case   isnull( [Rule_karpermah2]	    ,'0') when 0 then '' else cast( [Rule_karpermah2]		as nvarchar(max)) end as 'n085' ,
case   isnull( [Rule_karpermah3]	    ,'0') when 0 then '' else cast( [Rule_karpermah3]		as nvarchar(max)) end as 'n086' ,
case   isnull( [Rule_karpermah4]	    ,'0') when 0 then '' else cast( [Rule_karpermah4]		as nvarchar(max)) end as 'n087' ,
case   isnull( [Rule_karpermah5]	    ,'0') when 0 then '' else cast( [Rule_karpermah5]		as nvarchar(max)) end as 'n088' ,
case   isnull( [Rule_karpermah6]	    ,'0') when 0 then '' else cast( [Rule_karpermah6]		as nvarchar(max)) end as 'n089' ,
case   isnull( [Rule_karpermah7]	    ,'0') when 0 then '' else cast( [Rule_karpermah7]		as nvarchar(max)) end as 'n090' ,
case   isnull( [Rule_karpermah8]	    ,'0') when 0 then '' else cast( [Rule_karpermah8]		as nvarchar(max)) end as 'n091' ,
case   isnull( [Rule_karpermah9]	    ,'0') when 0 then '' else cast( [Rule_karpermah9]		as nvarchar(max)) end as 'n092' ,
case   isnull( [Rule_karpermah10]	    ,'0') when 0 then '' else cast( [Rule_karpermah10]		as nvarchar(max)) end as 'n093' ,
case   isnull( [Rule_karpermah11]	    ,'0') when 0 then '' else cast( [Rule_karpermah11]		as nvarchar(max)) end as 'n094' ,
case   isnull( [Rule_karpermah12]	    ,'0') when 0 then '' else cast( [Rule_karpermah12]		as nvarchar(max)) end as 'n095' ,
case   isnull( [Rule_IsRound]			,'0') when 0 then '' else cast( [Rule_IsRound]			as nvarchar(max)) end as 'n096' ,
case   isnull( [Rule_RoundTime]			,'0') when 0 then '' else cast( [Rule_RoundTime]		as nvarchar(max)) end as 'n097' ,
case   isnull( [Rule_RoundType]			,'0') when 0 then '' else cast( [Rule_RoundType]		as nvarchar(max)) end as 'n098' ,
case   isnull( [Rule_IsRoundCalc]	    ,'0') when 0 then '' else cast( [Rule_IsRoundCalc]		as nvarchar(max)) end as 'n099' ,
case   isnull( [Rule_RoundTimeCalc]	    ,'0') when 0 then '' else cast( [Rule_RoundTimeCalc]	as nvarchar(max)) end as 'n100' ,
case   isnull( [Rule_RoundTypeCalc]	    ,'0') when 0 then '' else cast( [Rule_RoundTypeCalc]	as nvarchar(max)) end as 'n101' ,
case   isnull( [Rule_IsRoundmonth]	    ,'0') when 0 then '' else cast( [Rule_IsRoundmonth]		as nvarchar(max)) end as 'n102' ,
case   isnull( [Rule_RoundTimemonth]	,'0') when 0 then '' else cast( [Rule_RoundTimemonth]	as nvarchar(max)) end as 'n103' ,
case   isnull( [Rule_RoundTypemonth]	,'0') when 0 then '' else cast( [Rule_RoundTypemonth]	as nvarchar(max)) end as 'n104' ,
case   isnull( [Rule_GHMH]				,'0') when 0 then '' else cast( [Rule_GHMH]				as nvarchar(max)) end as 'n105' , 
case   isnull( [Rule_GDMD]				,'0') when 0 then '' else cast( [Rule_GDMD]				as nvarchar(max)) end as 'n106' , 
case   isnull( [Rule_ghmhm]				,'0') when 0 then '' else cast( [Rule_ghmhm]			as nvarchar(max)) end as 'n107' , 
case   isnull( [Rule_GKar]				,'0') when 0 then '' else cast( [Rule_GKar]				as nvarchar(max)) end as 'n108' , 
case   isnull( [Rule_outinworkmax]	    ,'0') when 0 then '' else cast( [Rule_outinworkmax]		as nvarchar(max)) end as 'n109' ,
case   isnull( [Rule_T1E2D]				,'0') when 0 then '' else cast( [Rule_T1E2D]			as nvarchar(max)) end as 'n110' , 
case   isnull( [Rule_T2E1D]				,'0') when 0 then '' else cast( [Rule_T2E1D]			as nvarchar(max)) end as 'n111' , 
case   isnull( [Rule_T1e2b]				,'0') when 0 then '' else cast( [Rule_T1e2b]			as nvarchar(max)) end as 'n112' , 
case   isnull( [Rule_EzJomehEMor]	    ,'0') when 0 then '' else cast( [Rule_EzJomehEMor]		as nvarchar(max)) end as 'n113' ,
case   isnull( [Rule_EztnoJomehEMor]	,'0') when 0 then '' else cast( [Rule_EztnoJomehEMor]	as nvarchar(max)) end as 'n114' ,
case   isnull( [Rule_gdez]				,'0') when 0 then '' else cast( [Rule_gdez]				as nvarchar(max)) end as 'n115' , 
case   isnull( [Rule_mojerror]			,'0') when 0 then '' else cast( [Rule_mojerror]			as nvarchar(max)) end as 'n116' ,
case   isnull( [Rule_TED]				,'0') when 0 then '' else cast( [Rule_TED]				as nvarchar(max)) end as 'n117' , 
case   isnull( [Rule_T1E2M]				,'0') when 0 then '' else cast( [Rule_T1E2M]			as nvarchar(max)) end as 'n118' , 
case   isnull( [Rule_takhirmo]			,'0') when 0 then '' else cast( [Rule_takhirmo]			as nvarchar(max)) end as 'n119' ,
case   isnull( [Rule_tajilmo]			,'0') when 0 then '' else cast( [Rule_tajilmo]			as nvarchar(max)) end as 'n120' ,
case   isnull( [Rule_InCard]			,'0') when 0 then '' else cast( [Rule_InCard]			as nvarchar(max)) end as 'n121' , 
case   isnull( [Rule_OutCard]			,'0') when 0 then '' else cast( [Rule_OutCard]			as nvarchar(max)) end as 'n122' ,
case   isnull( [Rule_addyignore]	    ,'0') when 0 then '' else cast( [Rule_addyignore]		as nvarchar(max)) end as 'n123' ,
case   isnull( [Rule_fixstation]	    ,'0') when 0 then '' else cast( [Rule_fixstation]		as nvarchar(max)) end as 'n124' ,
case   isnull( [Rule_trdnear]			,'0') when 0 then '' else cast( [Rule_trdnear]			as nvarchar(max)) end as 'n125' ,
case   isnull( [Rule_NoHand]			,'0') when 0 then '' else cast( [Rule_NoHand]			as nvarchar(max)) end as 'n126' , 
case   isnull( [Rule_Zahab]				,'0') when 0 then '' else cast( [Rule_Zahab]			as nvarchar(max)) end as 'n127' , 
case   isnull( [Rule_Zahabt]			,'0') when 0 then '' else cast( [Rule_Zahabt]			as nvarchar(max)) end as 'n128' , 
case   isnull( [Rule_Zahabm]			,'0') when 0 then '' else cast( [Rule_Zahabm]			as nvarchar(max)) end as 'n129' , 
case   isnull( [Rule_Zahabtrd]			,'0') when 0 then '' else cast( [Rule_Zahabtrd]			as nvarchar(max)) end as 'n130' ,
case   isnull( [Rule_ghaza]				,'0') when 0 then '' else cast( [Rule_ghaza]			as nvarchar(max)) end as 'n131' , 
case   isnull( [Rule_ghazat]			,'0') when 0 then '' else cast( [Rule_ghazat]			as nvarchar(max)) end as 'n132' , 
case   isnull( [Rule_ghazam]			,'0') when 0 then '' else cast( [Rule_ghazam]			as nvarchar(max)) end as 'n133' , 
case   isnull( [Rule_Ghazatrd]			,'0') when 0 then '' else cast( [Rule_Ghazatrd]			as nvarchar(max)) end as 'n134' ,
case   isnull( [Rule_In1_Out2]			,'0') when 0 then '' else cast( [Rule_In1_Out2]			as nvarchar(max)) end as 'n135' ,
case   isnull( [Rule_In1_Out2_28]	    ,'0') when 0 then '' else cast( [Rule_In1_Out2_28]		as nvarchar(max)) end as 'n136' ,
case   isnull( [Rule_outinwork]			,'0') when 0 then '' else cast( [Rule_outinwork]		as nvarchar(max)) end as 'n137' ,
case   isnull( [Rule_mghez]				,'0') when 0 then '' else cast( [Rule_mghez]			as nvarchar(max)) end as 'n138' , 
case   isnull( [Rule_StartDay]			,'0') when 0 then '' else cast( [Rule_StartDay]			as nvarchar(max)) end as 'n139' ,
case   isnull( [Rule_StartNight]	    ,'0') when 0 then '' else cast( [Rule_StartNight]		as nvarchar(max)) end as 'n140' ,
case   isnull( [Rule_Night]				,'0') when 0 then '' else cast( [Rule_Night]			as nvarchar(max)) end as 'n141' , 
case   isnull( [Rule_Shrmarz]			,'0') when 0 then '' else cast( [Rule_Shrmarz]			as nvarchar(max)) end as 'n142' ,
case   isnull( [Rule_Shrfix]			,'0') when 0 then '' else cast( [Rule_Shrfix]			as nvarchar(max)) end as 'n143' , 
case   isnull( [Rule_cbtatil]			,'0') when 0 then '' else cast( [Rule_cbtatil]			as nvarchar(max)) end as 'n144' ,
case   isnull( [Rule_NaharFrom]			,'0') when 0 then '' else cast( [Rule_NaharFrom]		as nvarchar(max)) end as 'n145' ,
case   isnull( [Rule_NaharTo]			,'0') when 0 then '' else cast( [Rule_NaharTo]			as nvarchar(max)) end as 'n146' ,
case   isnull( [Rule_NaharLimit]	    ,'0') when 0 then '' else cast( [Rule_NaharLimit]		as nvarchar(max)) end as 'n147' ,
case   isnull( [Rule_Startvijeh]	    ,'0') when 0 then '' else cast( [Rule_Startvijeh]		as nvarchar(max)) end as 'n148' ,
case   isnull( [Rule_endvijeh]			,'0') when 0 then '' else cast( [Rule_endvijeh]			as nvarchar(max)) end as 'n149' ,
case   isnull( [Rule_SahariFrom]	    ,'0') when 0 then '' else cast( [Rule_SahariFrom]		as nvarchar(max)) end as 'n150' ,
case   isnull( [Rule_SahariTo]			,'0') when 0 then '' else cast( [Rule_SahariTo]			as nvarchar(max)) end as 'n151' ,
case   isnull( [Rule_SobhanehFrom]	    ,'0') when 0 then '' else cast( [Rule_SobhanehFrom]		as nvarchar(max)) end as 'n152' ,
case   isnull( [Rule_SobhanehTo]	    ,'0') when 0 then '' else cast( [Rule_SobhanehTo]		as nvarchar(max)) end as 'n153' ,
case   isnull( [Rule_nahar1From]	    ,'0') when 0 then '' else cast( [Rule_nahar1From]		as nvarchar(max)) end as 'n154' ,
case   isnull( [Rule_nahar1To]			,'0') when 0 then '' else cast( [Rule_nahar1To]			as nvarchar(max)) end as 'n155' ,
case   isnull( [Rule_ShamFrom]			,'0') when 0 then '' else cast( [Rule_ShamFrom]			as nvarchar(max)) end as 'n156' ,
case   isnull( [Rule_ShamTo]			,'0') when 0 then '' else cast( [Rule_ShamTo]			as nvarchar(max)) end as 'n157' , 
case   isnull( [Rule_Fridaylimit]	    ,'0') when 0 then '' else cast( [Rule_Fridaylimit]		as nvarchar(max)) end as 'n158' ,
case   isnull( [Rule_fridaybashift]	    ,'0') when 0 then '' else cast( [Rule_fridaybashift]	as nvarchar(max)) end as 'n159' ,
case   isnull( [Rule_fridaybishift]	    ,'0') when 0 then '' else cast( [Rule_fridaybishift]	as nvarchar(max)) end as 'n160' ,
--case   isnull( [Rule_sprulefdate]	    ,'0') when 0 then '' else cast( [Rule_sprulefdate]		as nvarchar(max)) end as 'n161' ,
--case   isnull( [Rule_spruleedate]	    ,'0') when 0 then '' else cast( [Rule_spruleedate]		as nvarchar(max)) end as 'n162' ,
case   isnull( [Rule_sprule]			,'0') when 0 then '' else cast( [Rule_sprule]			as nvarchar(max)) end as 'n163' ,
case   isnull( [Rule_mounfair]			,'0') when 0 then '' else cast( [Rule_mounfair]			as nvarchar(max)) end as 'n164' 

FROM [clock].[dbo].[rulesetc]



) as rule2
on  rule1.Rule_Code=rule2.rulecat_id

--where rulecat_id in(14,15,34,30,32)