//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExcell
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AtlasEntities : DbContext
    {
        public AtlasEntities()
            : base("name=AtlasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TA_Person> TA_Person { get; set; }
        public virtual DbSet<TA_PersonDetail> TA_PersonDetail { get; set; }
        public virtual DbSet<TA_Department> TA_Department { get; set; }
        public virtual DbSet<TA_EmploymentType> TA_EmploymentType { get; set; }
        public virtual DbSet<TA_Grade> TA_Grade { get; set; }
    }
}
