//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExcell
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_Department
    {
        public decimal dep_ID { get; set; }
        public string dep_Name { get; set; }
        public string dep_CustomCode { get; set; }
        public Nullable<decimal> dep_ParentID { get; set; }
        public string dep_ParentPath { get; set; }
    }
}
