//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExcell
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_EmploymentType
    {
        public TA_EmploymentType()
        {
            this.TA_Person = new HashSet<TA_Person>();
        }
    
        public decimal emply_ID { get; set; }
        public string emply_Name { get; set; }
        public string emply_CustomCode { get; set; }
    
        public virtual ICollection<TA_Person> TA_Person { get; set; }
    }
}
