//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExcell
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_Grade
    {
        public TA_Grade()
        {
            this.TA_Person = new HashSet<TA_Person>();
        }
    
        public decimal Grade_ID { get; set; }
        public string Grade_Name { get; set; }
        public string Grade_Description { get; set; }
    
        public virtual TA_Grade TA_Grade1 { get; set; }
        public virtual TA_Grade TA_Grade2 { get; set; }
        public virtual TA_Grade TA_Grade11 { get; set; }
        public virtual TA_Grade TA_Grade3 { get; set; }
        public virtual ICollection<TA_Person> TA_Person { get; set; }
    }
}
