//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExcell
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_PersonDetail
    {
        public TA_PersonDetail()
        {
            this.TA_Person = new HashSet<TA_Person>();
        }
    
        public decimal PrsDtl_ID { get; set; }
        public string PrsDtl_MeliCode { get; set; }
        public string PrsDtl_ShomareShenasname { get; set; }
        public string PrsDtl_BirthCertificate { get; set; }
        public string PrsDtl_Status { get; set; }
        public string PrsDtl_FatherName { get; set; }
        public Nullable<int> PrsDtl_MilitaryStatus { get; set; }
        public string PrsDtl_PlaceIssued { get; set; }
        public string PrsDtl_Tel { get; set; }
        public string PrsDtl_Address { get; set; }
        public string PrsDtl_BirthPlace { get; set; }
        public Nullable<System.DateTime> PrsDtl_BirthDate { get; set; }
        public string PrsDtl_Image { get; set; }
        public string PrsDtl_EmailAddress { get; set; }
        public string PrsDtl_MobileNumber { get; set; }
        public string PrsDtl_Grade { get; set; }
    
        public virtual ICollection<TA_Person> TA_Person { get; set; }
    }
}
