select * from TA_CalculationDateRangeTemplate 
select * from TA_ConceptTemplate 
select * from TA_CocneptTemplateParameter 
select * from TA_ConceptTemplateMapping 
select * from TA_RuleTemplate 
select * from TA_RuleTemplateParameter 
select * from TA_RuleConceptTemplate 
select * from TA_RuleTemplateMapping  
select * from TA_TemplateCondition 